"""alex auto

Revision ID: alextmp3d44b9285b9e
Revises: 20250925_0002
Create Date: 2026-09-25 11:22:40.709671

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'alextmp3d44b9285b9e'
down_revision: str | None = '20250925_0002'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
